USE crimedbtest;
SET GLOBAL foreign_key_checks = 0;
CREATE TABLE `neigborhood` (
  `idNeigborhood` int(11) NOT NULL AUTO_INCREMENT,
  `nname` varchar(100) DEFAULT NULL,
  `beat_idbeat` int(11) NOT NULL,
  PRIMARY KEY (`idNeigborhood`),
  KEY `fk_Neigborhood_beat1_idx` (`beat_idbeat`),
  CONSTRAINT `pk_beat` FOREIGN KEY (`beat_idbeat`) REFERENCES `beat` (`idbeat`)
) ENGINE=InnoDB AUTO_INCREMENT=243 DEFAULT CHARSET=utf8;


INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (1,'Adair Park',303);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (2,'Adams Park',409);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (3,'Adamsville',111);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (4,'Almond Park',110);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (5,'Amal Heights',307);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (6,'Ansley Park',502);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (7,'Arden/Habersham',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (8,'Ardmore',207);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (9,'Argonne Forest',405);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (10,'Arlington Estates',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (11,'Ashley Courts',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (12,'Ashview Heights',101);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (13,'Atkins Park',601);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (14,'Atlanta Industrial Park',114);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (15,'Atlanta University Center',102);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (16,'Atlantic Station',501);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (17,'Audobon Forest',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (18,'Audobon Forest West',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (19,'Baker Hills',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (20,'Bakers Ferry',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (21,'Bankhead',105);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (22,'Bankhead Courts',114);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (23,'Bankhead/Bolton',114);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (24,'Beecher Hills',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (25,'Ben Hill',414);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (26,'Ben Hill Acres',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (27,'Ben Hill Forest',414);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (28,'Ben Hill Pines',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (29,'Ben Hill Terrace',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (30,'Benteen Park',607);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (31,'Berkeley Park',207);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (32,'Betmar LaVilla',307);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (33,'Blair Villa/Poole Creek',313);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (34,'Blandtown',203);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (35,'Bolton',204);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (36,'Bolton Hills',113);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (37,'Boulder Park',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (38,'Boulevard Heights',607);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (39,'Brandon',201);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (40,'Brentwood',414);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (41,'Briar Glen',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (42,'Brookhaven',209);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (43,'Brookview Heights',113);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (44,'Brookwood',207);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (45,'Brookwood Hills',207);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (46,'Browns Mill Park',310);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (47,'Buckhead Forest',208);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (48,'Buckhead Heights',210);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (49,'Buckhead Village',206);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (50,'Bush Mountain',402);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (51,'Butner/Tell',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (52,'Cabbagetown',606);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (53,'Campbellton Road',409);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (54,'Candler Park',608);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (55,'Capitol Gateway',605);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (56,'Capitol View',301);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (57,'Capitol View Manor',301);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (58,'Carey Park',113);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (59,'Carroll Heights',114);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (60,'Carver Hills',110);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (61,'Cascade Avenue/Road',403);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (62,'Cascade Green',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (63,'Cascade Heights',409);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (64,'Castleberry Hill',507);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (65,'Castlewood',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (66,'Center Hill',113);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (67,'Chalet Woods',405);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (68,'Channing Valley',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (69,'Chastain Park',202);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (70,'Chattahoochee',113);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (71,'Chosewood Park',305);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (72,'Collier Heights',109);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (73,'Collier Hills',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (74,'Collier Hills North',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (75,'Colonial Homes',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (76,'Cross Creek',204);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (77,'Custer/McDonough/Guice',607);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (78,'Deerwood',410);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (79,'Dixie Hills',108);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (80,'Downtown',510);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (81,'Druid Hills',608);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (82,'East Ardley Road',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (83,'East Atlanta',612);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (84,'East Chastain Park',209);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (85,'East Lake',611);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (86,'Edgewood',609);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (87,'Elmco Estates',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (88,'Englewood Manor',305);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (89,'English Avenue',103);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (90,'English Park',114);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (91,'Fairburn',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (92,'Fairburn Heights',114);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (93,'Fairburn Mays',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (94,'Fairburn Road/Wisteria Lane',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (95,'Fairburn Tell',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (96,'Fairway Acres',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (97,'Fernleaf',204);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (98,'Florida Heights',108);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (99,'Fort McPherson',403);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (100,'Fort Valley',410);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (101,'Garden Hills',206);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (102,'Georgia Tech',501);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (103,'Glenrose Heights',313);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (104,'Grant Park',605);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (105,'Green Acres Valley',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (106,'Green Forest Acres',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (107,'Greenbriar',411);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (108,'Greenbriar Village',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (109,'Grove Park',110);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (110,'Hammond Park',311);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (111,'Hanover West',204);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (112,'Harland Terrace',405);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (113,'Harris Chiles',104);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (114,'Harvel Homes Community',108);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (115,'Heritage Valley',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (116,'High Point',305);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (117,'Hills Park',203);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (118,'Home Park',501);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (119,'Horseshoe Community',409);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (120,'Hunter Hills',105);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (121,'Huntington',414);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (122,'Inman Park',602);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (123,'Ivan Hill',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (124,'Joyland',307);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (125,'Just Us',104);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (126,'Kings Forest',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (127,'Kingswood',202);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (128,'Kirkwood',305);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (129,'Knight Park/Howell Station',106);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (130,'Lake Claire',608);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (131,'Lake Estates',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (132,'Lakewood',308);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (133,'Lakewood Heights',307);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (134,'Laurens Valley',409);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (135,'Leila Valley',308);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (136,'Lenox',210);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (137,'Lincoln Homes',113);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (138,'Lindbergh/Morosgo',211);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (139,'Lindridge/Martin Manor',211);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (140,'Loring Heights',207);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (141,'Magnum Manor',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (142,'Margaret Mitchell',201);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (143,'Marietta Street Artery',504);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (144,'Mays',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (145,'Meadowbrook Forest',505);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (146,'Mechanicsville',303);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (147,'Mellwood',414);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (148,'Memorial Park',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (149,'Midtown',502);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (150,'Midwest Cascade',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (151,'Monroe Heights',113);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (152,'Morningside/Lenox Park',213);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (153,'Mozley Park',104);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (154,'Mt. Gilead Woods',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (155,'Mt. Paran Parkway',202);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (156,'Mt. Paran/Northside',202);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (157,'Niskey Cove',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (158,'Niskey Lake',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (159,'North Buckhead',213);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (160,'Norwood Manor',308);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (161,'Oakcliff',111);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (162,'Oakland',605);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (163,'Oakland City',403);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (164,'Old Fairburn Village',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (165,'Old Fourth Ward',603);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (166,'Old Gordon',114);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (167,'Orchard Knob',312);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (168,'Ormewood Park',303);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (169,'Paces',201);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (170,'Peachtree Battle Alliance',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (171,'Peachtree Heights East',206);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (172,'Peachtree Heights West',206);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (173,'Peachtree Hills',211);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (174,'Peachtree Park',206);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (175,'Penelope Neighbors',108);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (176,'Peoplestown',304);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (177,'Perkerson',309);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (178,'Peyton Forest',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (179,'Piedmont Heights',213);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (180,'Pine Hills',210);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (181,'Pittsburgh',302);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (182,'Pleasant Hill',201);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (183,'Polar Rock',310);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (184,'Pomona Park',410);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (185,'Poncey-Highland',602);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (186,'Princeton Lakes',414);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (187,'Randall Mill',202);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (188,'Rebel Valley Forest',313);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (189,'Regency Trace',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (190,'Reynoldstown',606);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (191,'Ridgecrest Forest',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (192,'Ridgedale Park',210);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (193,'Ridgewood Heights',201);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (194,'Riverside',203);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (195,'Rockdale',110);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (196,'Rosedale Heights',308);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (197,'Rue Royal',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (198,'Sandlewood Estates',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (199,'Scotts Crossing',113);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (200,'Sherwood Forest',502);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (201,'South Atlanta',305);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (202,'South River Gardens',313);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (203,'South Tuxedo Park',206);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (204,'Southwest',412);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (205,'Springlake',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (206,'State Facility',607);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (207,'Summerhill',304);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (208,'Swallow Circle/Baywood',310);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (209,'Sweet Auburn',604);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (210,'Sylvan Hills',306);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (211,'Tampa Park',414);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (212,'The Villages at Carver',305);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (213,'The Villages at Castleberry H',101);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (214,'The Villages at East Lake',611);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (215,'Thomasville Heights',308);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (216,'Tuxedo Park',202);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (217,'Underwood Hills',204);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (218,'Venetian Hills',402);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (219,'Vine City',105);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (220,'Virginia Highland',601);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (221,'Washington Park',105);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (222,'Wesley Battle',201);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (223,'West End',401);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (224,'West Highlands',110);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (225,'West Lake',105);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (226,'West Manor',406);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (227,'West Paces Ferry/Northside',201);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (228,'Westhaven',111);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (229,'Westminster/Milmar',201);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (230,'Westover Plantation',204);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (231,'Westview',401);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (232,'Westwood Terrace',404);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (233,'Whitewater Creek',202);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (234,'Whittier Mill Village',203);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (235,'Wildwood (NPU-C)',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (236,'Wildwood (NPU-H)',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (237,'Wildwood Forest',413);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (238,'Wilson Mill Meadows',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (239,'Wisteria Gardens',407);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (240,'Woodfield',205);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (241,'Woodland Hills',607);
INSERT INTO crimedb.neigborhood(idNeigborhood,nname,beat_idbeat) VALUES (242,'Wyngate',205);
SET GLOBAL foreign_key_checks = 1;